language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "4.0"
  
sudo: required

# https://github.com/travis-ci/travis-ci/issues/1305#issuecomment-22143186
script: sudo $(which node) test.js
